"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/supabase/server";
import { acceptInviteSchema, answerSchema, capsuleSchema, inviteSchema, meetupSchema, momentSchema, moodSchema, nestSchema, noteSchema, uuid, wishlistSchema } from "@/validations/features";

async function auth(){const value=await requireUser();if(!value) redirect("/sign-in");return value}
function fail(path:string,message:string):never{redirect(`${path}?message=${encodeURIComponent(message)}`)}
function firstIssue(error:{issues:{message:string}[]}):string{return error.issues[0]?.message??"Check the form and try again."}

export async function createNest(form:FormData){const parsed=nestSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/onboarding",firstIssue(parsed.error));const {supabase}=await auth();const {error}=await supabase.rpc("create_nest",{p_name:parsed.data.name,p_relationship_start:parsed.data.relationship_start||null});if(error)fail("/onboarding",error.message);redirect("/home")}
export async function createInvite(form:FormData){const parsed=inviteSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/settings",firstIssue(parsed.error));const {supabase}=await auth();const {data,error}=await supabase.rpc("create_nest_invitation",{p_nest_id:parsed.data.nest_id,p_email:parsed.data.email||null});if(error)fail("/settings",error.message);redirect(`/settings?invite=${encodeURIComponent(String(data))}`)}
export async function acceptInvite(form:FormData){const parsed=acceptInviteSchema.safeParse(form.get("token"));if(!parsed.success)fail("/onboarding",firstIssue(parsed.error));const {supabase}=await auth();const {error}=await supabase.rpc("accept_nest_invitation",{p_token:parsed.data});if(error)fail("/onboarding",error.message);redirect("/home")}
export async function createMoment(form:FormData){
 const parsed=momentSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/moments/new",firstIssue(parsed.error));
 const files=form.getAll("photos").filter((value):value is File=>value instanceof File&&value.size>0);if(files.length>10)fail("/moments/new","Add no more than 10 photos at once.");
 const allowed=new Set(["image/jpeg","image/png","image/webp","image/avif"]);for(const file of files){if(!allowed.has(file.type)||file.size>15*1024*1024)fail("/moments/new","Photos must be JPG, PNG, WebP, or AVIF and no larger than 15 MB.")}
 const {supabase,user}=await auth();const {data:moment,error}=await supabase.from("moments").insert({...parsed.data,moment_at:new Date(parsed.data.moment_at).toISOString(),created_by:user.id,location_name:parsed.data.location_name||null,mood:parsed.data.mood||null}).select("id").single();if(error||!moment)fail("/moments/new","That moment couldn’t be saved.");
 for(const [index,file] of files.entries()){const extension=file.type.split("/")[1]?.replace("jpeg","jpg")??"jpg";const path=`${parsed.data.nest_id}/${user.id}/${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await supabase.storage.from("moment-media").upload(path,file,{contentType:file.type,upsert:false,cacheControl:"3600"});if(uploadError){await supabase.from("moments").delete().eq("id",moment.id);fail("/moments/new","A photo upload was interrupted, so the moment was not saved. Please try again.")}const {error:mediaError}=await supabase.from("moment_media").insert({nest_id:parsed.data.nest_id,moment_id:moment.id,storage_path:path,mime_type:file.type,alt_text:`Photo for ${parsed.data.title}`,sort_order:index});if(mediaError){await supabase.storage.from("moment-media").remove([path]);await supabase.from("moments").delete().eq("id",moment.id);fail("/moments/new","A photo could not be attached. Please try again.")}}
 revalidatePath("/moments");redirect("/moments")
}
export async function updateMoment(form:FormData){const id=uuid.safeParse(form.get("id"));const parsed=momentSchema.safeParse(Object.fromEntries(form));if(!id.success||!parsed.success)fail("/moments","Check the moment and try again.");const {supabase}=await auth();const {error}=await supabase.from("moments").update({...parsed.data,moment_at:new Date(parsed.data.moment_at).toISOString(),location_name:parsed.data.location_name||null,mood:parsed.data.mood||null}).eq("id",id.data);if(error)fail("/moments","That moment couldn’t be updated.");revalidatePath("/moments");redirect("/moments")}
export async function deleteMoment(form:FormData){const id=uuid.safeParse(form.get("id"));if(!id.success)fail("/moments","Invalid moment.");const {supabase}=await auth();const {error}=await supabase.from("moments").delete().eq("id",id.data);if(error)fail("/moments","That moment couldn’t be removed.");revalidatePath("/moments")}
export async function setMood(form:FormData){const parsed=moodSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/home",firstIssue(parsed.error));const {supabase,user}=await auth();const localDate=new Intl.DateTimeFormat("en-CA",{timeZone:parsed.data.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const {error}=await supabase.from("daily_moods").upsert({nest_id:parsed.data.nest_id,user_id:user.id,local_date:localDate,mood:parsed.data.mood},{onConflict:"user_id,local_date"});if(error)fail("/home","Your mood couldn’t be saved.");revalidatePath("/home")}
export async function thinkOfPartner(form:FormData){const nestId=uuid.safeParse(form.get("nest_id"));if(!nestId.success)fail("/home","Invalid Nest.");const {supabase}=await auth();const {error}=await supabase.rpc("send_thinking_of_you",{p_nest_id:nestId.data});if(error)fail("/home",error.message);redirect("/home?message=Sent with love.")}
export async function createNote(form:FormData){const parsed=noteSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/notes",firstIssue(parsed.error));const {supabase,user}=await auth();const scheduled=Boolean(parsed.data.deliver_at);const {error}=await supabase.from("love_notes").insert({nest_id:parsed.data.nest_id,sender_id:user.id,recipient_id:parsed.data.recipient_id,body:parsed.data.body,theme:parsed.data.theme,status:scheduled?"scheduled":"delivered",deliver_at:parsed.data.deliver_at?new Date(parsed.data.deliver_at).toISOString():new Date().toISOString(),delivered_at:scheduled?null:new Date().toISOString()});if(error)fail("/notes","Your note couldn’t be saved.");revalidatePath("/notes");redirect("/notes?message=Your note is safely on its way.")}
export async function createMeetup(form:FormData){const parsed=meetupSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/plans",firstIssue(parsed.error));const {supabase,user}=await auth();const {error}=await supabase.from("meetups").insert({...parsed.data,starts_at:new Date(parsed.data.starts_at).toISOString(),created_by:user.id});if(error)fail("/plans","The meetup couldn’t be saved.");revalidatePath("/plans");redirect("/plans")}
export async function createWishlistItem(form:FormData){const parsed=wishlistSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/plans",firstIssue(parsed.error));const {supabase,user}=await auth();const {error}=await supabase.from("wishlist_items").insert({...parsed.data,created_by:user.id});if(error)fail("/plans","That dream couldn’t be saved.");revalidatePath("/plans")}
export async function createCapsule(form:FormData){const parsed=capsuleSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/us",firstIssue(parsed.error));const {supabase,user}=await auth();const {error}=await supabase.from("time_capsules").insert({nest_id:parsed.data.nest_id,created_by:user.id,title:parsed.data.title,encrypted_content:parsed.data.content,unlock_at:new Date(parsed.data.unlock_at).toISOString(),target_timezone:parsed.data.timezone,strict_lock:true});if(error)fail("/us","The capsule couldn’t be sealed.");revalidatePath("/us")}
export async function answerQuestion(form:FormData){const parsed=answerSchema.safeParse(Object.fromEntries(form));if(!parsed.success)fail("/questions",firstIssue(parsed.error));const {supabase,user}=await auth();const {error}=await supabase.from("daily_question_answers").upsert({...parsed.data,user_id:user.id,answered_at:new Date().toISOString()},{onConflict:"nest_id,local_date,user_id"});if(error)fail("/questions","Your answer couldn’t be saved.");revalidatePath("/questions");redirect("/questions?message=Your answer is safe. It will open when both of you reply.")}
export async function markNotificationRead(form:FormData){const id=uuid.safeParse(form.get("id"));if(!id.success)return;const {supabase}=await auth();await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("id",id.data);revalidatePath("/notifications")}
export async function saveDateIdea(form:FormData){const nestId=uuid.safeParse(form.get("nest_id"));const ideaId=uuid.safeParse(form.get("idea_id"));if(!nestId.success||!ideaId.success)return;const {supabase,user}=await auth();await supabase.from("saved_date_ideas").upsert({nest_id:nestId.data,idea_id:ideaId.data,saved_by:user.id});revalidatePath("/together")}
export async function startChallenge(form:FormData){const nestId=uuid.safeParse(form.get("nest_id"));const challengeId=uuid.safeParse(form.get("challenge_id"));if(!nestId.success||!challengeId.success)return;const {supabase,user}=await auth();await supabase.from("nest_challenges").insert({nest_id:nestId.data,challenge_id:challengeId.data,started_by:user.id,starts_on:new Date().toISOString().slice(0,10)});revalidatePath("/together")}
export async function createMeetupTask(form:FormData){const nestId=uuid.safeParse(form.get("nest_id"));const meetupId=uuid.safeParse(form.get("meetup_id"));const title=String(form.get("title")??"").trim().slice(0,160);if(!nestId.success||!meetupId.success||!title)return;const {supabase,user}=await auth();await supabase.from("meetup_tasks").insert({nest_id:nestId.data,meetup_id:meetupId.data,created_by:user.id,title,category:String(form.get("category")??"Custom").slice(0,40)});revalidatePath("/plans")}
export async function toggleMeetupTask(form:FormData){const id=uuid.safeParse(form.get("id"));if(!id.success)return;const completed=form.get("completed")!=="true";const {supabase}=await auth();await supabase.from("meetup_tasks").update({completed}).eq("id",id.data);revalidatePath("/plans")}
export async function updateWishlistStatus(form:FormData){const id=uuid.safeParse(form.get("id"));const status=String(form.get("status"));if(!id.success||!["dream","planning","done"].includes(status))return;const {supabase}=await auth();await supabase.from("wishlist_items").update({status}).eq("id",id.data);revalidatePath("/plans")}
export async function convertWishlist(form:FormData){const id=uuid.safeParse(form.get("id"));if(!id.success)return;const {supabase}=await auth();const {error}=await supabase.rpc("convert_wishlist_to_moment",{p_item_id:id.data,p_moment_at:new Date().toISOString()});if(error)fail("/plans",error.message);revalidatePath("/plans");revalidatePath("/moments")}
export async function savePreferences(form:FormData){const {supabase,user}=await auth();const kinds=["love_note","thinking_of_you","mood","question_unlocked","challenge","meetup","important_date","capsule","wishlist","moment"];const notifications=Object.fromEntries(kinds.map(kind=>[kind,form.get(kind)==="on"]));await supabase.from("user_preferences").update({notifications}).eq("user_id",user.id);redirect("/settings?message=Preferences saved.")}
export async function createImportantDate(form:FormData){const nestId=uuid.safeParse(form.get("nest_id"));const title=String(form.get("title")??"").trim().slice(0,160);const eventDate=String(form.get("event_date")??"");if(!nestId.success||!title||!/\d{4}-\d{2}-\d{2}/.test(eventDate))return;const {supabase,user}=await auth();await supabase.from("important_dates").insert({nest_id:nestId.data,created_by:user.id,title,event_date:eventDate,timezone:String(form.get("timezone")??"UTC"),category:String(form.get("category")??"Custom").slice(0,50),recurring_yearly:form.get("recurring_yearly")==="on"});revalidatePath("/us")}
export async function updateProfile(form:FormData){const name=String(form.get("display_name")??"").trim().slice(0,60);const timezone=String(form.get("timezone")??"UTC").slice(0,80);const city=String(form.get("city")??"").trim().slice(0,100)||null;const birthday=String(form.get("birthday")??"")||null;if(name.length<2)fail("/settings","Your name needs at least two characters.");const {supabase,user}=await auth();const {error}=await supabase.from("profiles").update({display_name:name,timezone,city,birthday}).eq("id",user.id);if(error)fail("/settings","Your profile couldn’t be updated.");revalidatePath("/home");redirect("/settings?message=Profile saved.")}
